name: TowardsLife
description: An Open Source Thirukkural app built using Flutter and Firebase 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  get: 3.25.3
  flutter:
    sdk: flutter
  auto_animated: 
  flutter_hooks:
  get_storage:
  hive: ^1.4.4+1
  hive_flutter:
  firebase_core: 0.5.3
  cloud_firestore: 0.14.4
  cupertino_icons:

  
dev_dependencies:
  build_runner: 1.11.0
  hive_generator: 0.8.2
  flutter_test:
    sdk: flutter
  device_preview:
  flutter_launcher_icons: "^0.7.5"
  flutter_launcher_name: "^0.0.1"
  lint:
  test:
  

flutter_launcher_name:
  name: "Towards Life"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/tl.png"

flutter:
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/jsons/

  fonts:
    - family: NotoSansTamil
      fonts:
        - asset: assets/fonts/NotoSansTamil-Regular.ttf
        - asset: assets/fonts/NotoSansTamil-Bold.ttf
          weight: 700
    - family: ArimaMadurai
      fonts:
        - asset: assets/fonts/ArimaMadurai-Regular.ttf
        - asset: assets/fonts/ArimaMadurai-Medium.ttf
          weight: 700